#!/usr/bin/env python3
"""Self-contained evidence bundle (Architecture.md Sections 19, 23; roadmap
Phase 5 exit: "evidence bundle for the pilot produced and usable by a third
party").

Renders a single tracked document, `reports/bundle.md`, that embeds:

* a manifest of sha256 hashes for the durable artifacts;
* the per-block layer status vector (validity rule applied to current evidence);
* the full evidence records; and
* the current project views (trust boundary, calibration, discrepancy, impact,
  decisions).

Deterministic: the same repository state yields byte-identical output.

Usage:
    python3 scripts/bundle.py
    python3 scripts/bundle.py --check-report
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import status  # noqa: E402

ROOT = HERE.parent
REPORT = ROOT / "reports" / "bundle.md"
MANIFEST_PATHS = [
    "manuscript/MSEilenberg.tex",
    "blocks/registry.json",
    "blocks/hashes.json",
    "blocks/formal.json",
    "blocks/formal_graph.json",
    "blocks/lean_audit.json",
    "blocks/graph.json",
    "representation/pilot-encoding.md",
    "calibration/seeded.json",
    "calibration/generated.json",
    "calibration/baseline.json",
    "calibration/models.json",
    "calibration/verdicts.json",
    "blocks/treatment_tiers.json",
    "blocks/scope_decisions.json",
    "blocks/discrepancy_decisions.json",
    "blocks/notation.json",
    "blocks/ranking.json",
    "reconciliation/proposals.json",
    "decisions/standing.json",
    "journal/events.jsonl",
    "lean/lake-manifest.json",
    "lean/lean-toolchain",
    "schemas/evidence.schema.json",
]
VIEWS = [
    "reports/coverage.md",
    "reports/trust_boundary.md",
    "reports/sanity.md",
    "reports/calibration.md",
    "reports/discrepancy.md",
    "reports/impact.md",
    "reports/frontier.md",
    "reports/ranking.md",
    "reports/reconciliation.md",
    "reports/decisions.md",
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def manifest():
    rows = []
    for rel in MANIFEST_PATHS:
        p = ROOT / rel
        if p.exists():
            rows.append((rel, sha256(p)))
    for p in sorted((ROOT / "evidence").glob("*.json")):
        rows.append((str(p.relative_to(ROOT)), sha256(p)))
    return sorted(rows)


def status_table():
    registry = status.load_registry(ROOT / "blocks" / "registry.json")
    records = status.load_evidence(ROOT / "evidence")
    rep = {"encoding": status.hash_file(ROOT / "representation" / "pilot-encoding.md")}
    grouped = status.group_by_block_layer(records)
    tiers = status.load_default_tiers()
    lines = ["| block | layer | status | current | stale |", "|---|---|---|---|---|"]
    for block in sorted(grouped):
        for layer, st in sorted(status.block_status(grouped[block], registry, rep,
                                                    tiers=tiers, block=block).items()):
            lines.append(
                f"| `{block}` | {layer} | {st['status']} | {st['current']} | {st['stale']} |"
            )
    return "\n".join(lines)


def render():
    lines = [
        "# MSLang pilot -- evidence bundle",
        "",
        "Generated by `scripts/bundle.py`; deterministic snapshot of the durable",
        "artifacts, the current evidence, and the project views. A referee can read",
        "this document alone, then check any hash in the manifest against the",
        "repository.",
        "",
        "## Manifest (sha256)",
        "",
        "| artifact | sha256 |",
        "|---|---|",
    ]
    for rel, h in manifest():
        lines.append(f"| `{rel}` | `{h}` |")
    lines += ["", "## Status (validity rule applied to current evidence)", "", status_table(), ""]
    lines += ["## Evidence records", ""]
    for p in sorted((ROOT / "evidence").glob("*.json")):
        rec = json.loads(p.read_text(encoding="utf-8"))
        lines += [f"### {rec.get('evidence_id', p.name)}", "", "```json",
                  json.dumps(rec, indent=2, sort_keys=True), "```", ""]
    for rel in VIEWS:
        p = ROOT / rel
        if p.exists():
            lines += [f"## {rel}", "", p.read_text(encoding="utf-8").rstrip(), ""]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)
    text = render()
    if args.check_report:
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != text:
            print(f"bundle: drift in {REPORT.relative_to(ROOT)}")
            return 1
        print("bundle: current")
        return 0
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(text, encoding="utf-8")
    print(f"bundle: wrote {REPORT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
