#!/usr/bin/env python3
"""Self-contained evidence bundle (Architecture.md Sections 19, 23; roadmap
Phase 5 exit: "evidence bundle for the pilot produced and usable by a third
party").

Renders a single tracked document, `reports/bundle.md`, that embeds:

* a manifest of sha256 hashes for the durable artifacts;
* the per-block layer status vector (validity rule applied to current evidence);
* the full evidence records; and
* the current project views (trust boundary, calibration, discrepancy, impact,
  decisions).

Deterministic: the same repository state yields byte-identical output.

The manifest and view scope are resolved from the project registry, so a second
manuscript project gets its own bundle; the default project's paths are
unchanged (OpenSpec change `add-mscong-project`).

Usage:
    python3 scripts/bundle.py
    python3 scripts/bundle.py --project mscong
    python3 scripts/bundle.py --check-report
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import projects as pj  # noqa: E402
import status  # noqa: E402

ROOT = HERE.parent

# Project-scoped manifest entries, resolved from the registry (relative to the
# repository root) so the default project's rows are unchanged.
PROJECT_MANIFEST_KEYS = (
    "manuscript",
    "registry",
    "hashes",
    "lean_formal",
    "lean_formal_graph",
    "lean_audit",
    "graph",
    "representation",
    "journal",
)

# Artifacts shared by the workspace (not per project).
SHARED_MANIFEST_PATHS = [
    "calibration/seeded.json",
    "calibration/generated.json",
    "calibration/baseline.json",
    "calibration/models.json",
    "calibration/verdicts.json",
    "blocks/treatment_tiers.json",
    "blocks/scope_decisions.json",
    "blocks/discrepancy_decisions.json",
    "blocks/notation.json",
    "blocks/ranking.json",
    "reconciliation/proposals.json",
    "decisions/standing.json",
    "lean/lake-manifest.json",
    "lean/lean-toolchain",
    "schemas/evidence.schema.json",
]
VIEW_NAMES = [
    "coverage.md",
    "trust_boundary.md",
    "sanity.md",
    "calibration.md",
    "discrepancy.md",
    "impact.md",
    "frontier.md",
    "ranking.md",
    "reconciliation.md",
    "decisions.md",
]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def project_paths(project_id: str):
    """Resolve the bundle-relevant paths for a project from the registry."""
    entry = pj.get(project_id)
    blocks_dir = entry["blocks_dir"]
    reports_dir = entry["reports_dir"]
    return {
        "entry": entry,
        "registry": entry.get("registry") or blocks_dir / "registry.json",
        "evidence_dir": entry["evidence_dir"],
        "representation": entry.get("representation"),
        "reports_dir": reports_dir,
        "report": reports_dir / "bundle.md",
        "views": [reports_dir / name for name in VIEW_NAMES],
    }


def manifest(paths):
    rows = []
    entry = paths["entry"]
    for key in PROJECT_MANIFEST_KEYS:
        p = entry.get(key)
        if p is not None and Path(p).exists():
            rows.append((str(Path(p).relative_to(ROOT)), sha256(p)))
    for rel in SHARED_MANIFEST_PATHS:
        p = ROOT / rel
        if p.exists():
            rows.append((rel, sha256(p)))
    evidence_dir = paths["evidence_dir"]
    if Path(evidence_dir).is_dir():
        for p in sorted(Path(evidence_dir).glob("*.json")):
            rows.append((str(p.relative_to(ROOT)), sha256(p)))
    return sorted(rows)


def status_table(paths):
    registry = status.load_registry(paths["registry"])
    records = status.load_evidence(paths["evidence_dir"])
    rep = {}
    if paths["representation"] is not None and Path(paths["representation"]).exists():
        rep = {"encoding": status.hash_file(paths["representation"])}
    grouped = status.group_by_block_layer(records)
    tiers = status.load_default_tiers()
    lines = ["| block | layer | status | current | stale |", "|---|---|---|---|---|"]
    for block in sorted(grouped):
        for layer, st in sorted(status.block_status(grouped[block], registry, rep,
                                                    tiers=tiers, block=block).items()):
            lines.append(
                f"| `{block}` | {layer} | {st['status']} | {st['current']} | {st['stale']} |"
            )
    return "\n".join(lines)


def render(project_id: str):
    paths = project_paths(project_id)
    lines = [
        "# MSLang pilot -- evidence bundle",
        "",
        "Generated by `scripts/bundle.py`; deterministic snapshot of the durable",
        "artifacts, the current evidence, and the project views. A referee can read",
        "this document alone, then check any hash in the manifest against the",
        "repository.",
        "",
        "## Manifest (sha256)",
        "",
        "| artifact | sha256 |",
        "|---|---|",
    ]
    for rel, h in manifest(paths):
        lines.append(f"| `{rel}` | `{h}` |")
    lines += ["", "## Status (validity rule applied to current evidence)", "", status_table(paths), ""]
    lines += ["## Evidence records", ""]
    evidence_dir = Path(paths["evidence_dir"])
    if evidence_dir.is_dir():
        for p in sorted(evidence_dir.glob("*.json")):
            rec = json.loads(p.read_text(encoding="utf-8"))
            lines += [f"### {rec.get('evidence_id', p.name)}", "", "```json",
                      json.dumps(rec, indent=2, sort_keys=True), "```", ""]
    for p in paths["views"]:
        if Path(p).exists():
            lines += [
                f"## {Path(p).relative_to(ROOT)}",
                "",
                Path(p).read_text(encoding="utf-8").rstrip(),
                "",
            ]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--project", default=None, help="project id (default: registry default)")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    project_id = args.project or pj.default_project()
    paths = project_paths(project_id)
    report = paths["report"]
    text = render(project_id)
    if args.check_report:
        actual = report.read_text(encoding="utf-8") if report.exists() else None
        if actual != text:
            print(f"bundle: drift in {report.relative_to(ROOT)}")
            return 1
        print("bundle: current")
        return 0
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(text, encoding="utf-8")
    print(f"bundle: wrote {report.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
