#!/usr/bin/env python3
"""Seeded-mismatch calibration (Architecture.md Section 11.4).

Audit reliability is measured, not assumed.  The corpus
``calibration/seeded.json`` pairs each audited contract with a read-back that
is either the control (the audited read-back) or a mutation of it (one named
change: direction flip, reversed conclusion, swapped saturation order,
quantifier change, dropped hypothesis, weakened conclusion, encoding change).
The comparator (Section 11.2 stage 2) is run blind on every case; a mutation is
*detected* when the returned outcome is not ``equivalent``.

This tool does not run the audit itself; it checks the corpus, ingests a
verdicts file produced by an actual audit run, and reports detection rates per
mutation type and the control false-positive rate.

Usage:
    python3 scripts/calibration.py --self-test
    python3 scripts/calibration.py --list
    python3 scripts/calibration.py --verdicts calibration/verdicts.json
    python3 scripts/calibration.py --verdicts calibration/verdicts.json --report
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SEED = ROOT / "calibration" / "seeded.json"
DEFAULT_VERDICTS = ROOT / "calibration" / "verdicts.json"
REPORT = ROOT / "reports" / "calibration.md"
REQUIRED = {"id", "block", "type", "expect", "contract", "readback"}


def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def corpus_errors(seed):
    errors = []
    bases = seed.get("base_readbacks", {})
    cases = seed.get("cases", [])
    seen = set()
    for c in cases:
        cid = c.get("id", "?")
        missing = REQUIRED - set(c)
        if missing:
            errors.append(f"{cid}: missing fields {sorted(missing)}")
            continue
        if cid in seen:
            errors.append(f"{cid}: duplicate id")
        seen.add(cid)
        block = c["block"]
        if block not in bases:
            errors.append(f"{cid}: no base_readback for {block}")
            continue
        if c["type"] == "control":
            if c["expect"] != "equivalent":
                errors.append(f"{cid}: control must expect 'equivalent'")
            if c["readback"].strip() != bases[block].strip():
                errors.append(f"{cid}: control read-back differs from its base")
        else:
            if c["expect"] == "equivalent":
                errors.append(f"{cid}: a mutation must not expect 'equivalent'")
            if c["readback"].strip() == bases[block].strip():
                errors.append(f"{cid}: mutation read-back equals its base")
    return errors


def is_detected(outcome):
    return outcome.strip().lower() != "equivalent"


def summarize(seed, verdicts):
    """Return (per_type, controls, overall) detection statistics."""
    cases = seed["cases"]
    per_type = {}
    controls = {"n": 0, "false_positive": 0}
    total = {"n": 0, "detected": 0, "unrun": 0}
    for c in cases:
        outcome = verdicts.get(c["id"])
        if outcome is None:
            total["unrun"] += 1
            if c["type"] == "control":
                controls["n"] += 1
            else:
                per_type.setdefault(c["type"], {"n": 0, "detected": 0})["n"] += 1
            continue
        detected = is_detected(outcome)
        if c["type"] == "control":
            controls["n"] += 1
            if detected:
                controls["false_positive"] += 1
        else:
            slot = per_type.setdefault(c["type"], {"n": 0, "detected": 0})
            slot["n"] += 1
            slot["detected"] += 1 if detected else 0
            total["n"] += 1
            total["detected"] += 1 if detected else 0
    return per_type, controls, total


def render_report(seed, verdicts, audit_note):
    per_type, controls, total = summarize(seed, verdicts)
    lines = [
        "# Calibration report (Section 11.4)",
        "",
        "Generated by `scripts/calibration.py` from `calibration/seeded.json` and",
        "`calibration/verdicts.json`. A mutation is *detected* when the blind",
        "comparator returns an outcome other than `equivalent`. Controls are the",
        "audited read-backs; a control judged non-equivalent is a false positive.",
        "",
        audit_note.rstrip(),
        "",
        "## Detection by mutation type",
        "",
        "| mutation type | cases | detected | rate |",
        "|---|---|---|---|",
    ]
    for t in sorted(per_type):
        s = per_type[t]
        rate = "n/a" if s["n"] == 0 else f"{s['detected'] / s['n']:.2f}"
        lines.append(f"| {t} | {s['n']} | {s['detected']} | {rate} |")
    lines += [
        "",
        "## Controls (false positives)",
        "",
        f"- controls run: {controls['n']}",
        f"- false positives: {controls['false_positive']}",
        "",
        "## Overall (mutations only)",
        "",
        f"- mutations run: {total['n']}",
        f"- detected: {total['detected']}",
        f"- unrun cases: {total['unrun']}",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--seed", default=str(DEFAULT_SEED))
    ap.add_argument("--verdicts", default=str(DEFAULT_VERDICTS))
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    seed = load_json(args.seed)

    if args.self_test:
        errors = corpus_errors(seed)
        for e in errors:
            print(f"FAIL {e}")
        if errors:
            return 1
        print(f"calibration: corpus OK ({len(seed['cases'])} cases)")
        return 0

    if args.list:
        for c in seed["cases"]:
            print(f"{c['id']}  {c['block']:8s} {c['type']}")
        return 0

    verdicts = {}
    vpath = Path(args.verdicts)
    if vpath.exists():
        doc = load_json(vpath)
        verdicts = doc.get("verdicts", doc) if isinstance(doc, dict) else doc
    per_type, controls, total = summarize(seed, verdicts)
    print(
        f"calibration: {total['n']} mutation(s), {total['detected']} detected; "
        f"{controls['n']} control(s), {controls['false_positive']} false positive(s)"
    )
    for t in sorted(per_type):
        s = per_type[t]
        print(f"  {t:22s} {s['detected']}/{s['n']}")

    if args.report:
        note = seed.get("audit_note", "")
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(render_report(seed, verdicts, note), encoding="utf-8")
        print(f"calibration: wrote {REPORT.relative_to(ROOT)}")
    if args.check_report:
        expected = render_report(seed, verdicts, seed.get("audit_note", ""))
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != expected:
            print("calibration: report drift in reports/calibration.md")
            return 1
        print("calibration: report current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
