#!/usr/bin/env python3
"""Decision queue (Architecture.md Sections 16.4, 19).

Consolidates the decisions awaiting the author from two sources:

* `decisions/standing.json` -- standing reserved decisions (contracts,
  representation, scope, tooling);
* the append-only journal -- `escalation_opened` events not matched by an
  `escalation_resolved` event (matched by `details.escalation`).

Renders `reports/decisions.md`; `--check-report` detects drift.

Usage:
    python3 scripts/decisions.py
    python3 scripts/decisions.py --report
    python3 scripts/decisions.py --check-report
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STANDING = ROOT / "decisions" / "standing.json"
JOURNAL = ROOT / "journal" / "events.jsonl"
REPORT = ROOT / "reports" / "decisions.md"


def load_standing(path):
    return json.loads(Path(path).read_text(encoding="utf-8")).get("decisions", [])


def open_escalations(path):
    opened, resolved = [], set()
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        ev = json.loads(line)
        if ev.get("kind") == "escalation_opened":
            opened.append(ev)
        elif ev.get("kind") == "escalation_resolved":
            ref = (ev.get("details") or {}).get("escalation")
            if ref:
                resolved.add(ref)
    return [e for e in opened if e.get("event_id") not in resolved]


def render_report(standing, escalations):
    lines = [
        "# Decision queue (Sections 16.4, 19)",
        "",
        "Generated by `scripts/decisions.py`. Everything here awaits the author;",
        "agents present options and stop.",
        "",
        "## Standing decisions",
        "",
        "| id | category | decision |",
        "|---|---|---|",
    ]
    for d in standing:
        lines.append(f"| `{d['id']}` | {d['category']} | {d['decision']} |")
    if not standing:
        lines.append("| _none_ | | |")
    lines += ["", "## Open escalations (journal)", "", "| event | block | class | summary |", "|---|---|---|---|"]
    for e in escalations:
        details = e.get("details") or {}
        lines.append(
            "| {ev} | `{block}` | {cls} | {summary} |".format(
                ev=e.get("event_id", "?"),
                block=e.get("block", "-"),
                cls=details.get("change_class", "-"),
                summary=e.get("summary", ""),
            )
        )
    if not escalations:
        lines.append("| _none_ | | | |")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--standing", default=str(STANDING))
    ap.add_argument("--journal", default=str(JOURNAL))
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    standing = load_standing(args.standing)
    escalations = open_escalations(args.journal)
    text = render_report(standing, escalations)

    if args.check_report:
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != text:
            print(f"decisions: report drift in {REPORT.relative_to(ROOT)}")
            return 1
        print("decisions: report current")
        return 0

    print(f"decisions: {len(standing)} standing, {len(escalations)} open escalation(s)")
    for d in standing:
        print(f"  {d['id']:24s} {d['category']}")
    for e in escalations:
        print(f"  {e.get('event_id','?'):10s} {e.get('block','-')}")

    if args.report:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(text, encoding="utf-8")
        print(f"decisions: wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
