#!/usr/bin/env python3
"""Graph discrepancy report (Architecture.md Sections 12.2, 19).

Two dependency graphs exist: the informal one (``blocks/graph.json``, confirmed
`uses_statement`/`uses_definition` edges) and the formal one
(``blocks/formal_graph.json``, `formal_uses`). Their differences are the
concrete mechanism behind "formalization improves the mathematics":

* a **formal-only** edge -- a formal proof uses a fact the informal proof does
  not cite: a possible hidden dependency or unstated step;
* an **informal-only** edge (both endpoints mapped) -- the informal text cites a
  block the formal proof never uses: a possible superfluous hypothesis or an
  argument that can be simplified.

Only blocks with a formal counterpart (the mapped universe) are compared;
unmapped informal edges are reported separately as "not yet mapped".

Usage:
    python3 scripts/discrepancy.py
    python3 scripts/discrepancy.py --report
    python3 scripts/discrepancy.py --check-report
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEPENDENCY_KINDS = {"uses_statement", "uses_definition"}
REPORT = ROOT / "reports" / "discrepancy.md"


def load_edges(path, kinds=None):
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    out = []
    for e in doc.get("edges", []):
        if kinds and e.get("kind") not in kinds:
            continue
        if e.get("confirmed") is False:
            continue
        out.append((e["from"], e["to"]))
    return out


def compare(informal, formal):
    universe = {b for e in formal for b in e}
    fset = set(formal)
    iset = {(a, b) for (a, b) in informal if a in universe and b in universe}
    unmapped = sorted({(a, b) for (a, b) in informal if a not in universe or b not in universe})
    return {
        "universe": sorted(universe),
        "formal_only": sorted(fset - iset),
        "informal_only": sorted(iset - fset),
        "agree": sorted(fset & iset),
        "unmapped": unmapped,
    }


def render_report(d, notes=None):
    notes = notes or {}
    lines = [
        "# Dependency-graph discrepancy report (Sections 12.2, 19)",
        "",
        "Generated by `scripts/discrepancy.py`. Compared over the blocks with a",
        "formal counterpart (the mapped universe); `formal_uses` edges are",
        "extracted from Lean source, informal edges are confirmed `\\ref`/`\\uses`",
        "and symbol/prose edges.",
        "",
        f"Mapped blocks: {', '.join('`'+b+'`' for b in d['universe']) or 'none'}",
        "",
        "## Formal-only (possible hidden dependency / unstated step)",
        "",
        "| from | to |",
        "|---|---|",
    ]
    for a, b in d["formal_only"]:
        lines.append(f"| `{a}` | `{b}` |")
    if not d["formal_only"]:
        lines.append("| _none_ | |")
    lines += ["", "## Informal-only, mapped (possible simplification)", "", "| from | to |", "|---|---|"]
    for a, b in d["informal_only"]:
        lines.append(f"| `{a}` | `{b}` |")
    if not d["informal_only"]:
        lines.append("| _none_ | |")
    lines += ["", "## Agreeing edges", "", "| from | to |", "|---|---|"]
    for a, b in d["agree"]:
        lines.append(f"| `{a}` | `{b}` |")
    if not d["agree"]:
        lines.append("| _none_ | |")
    lines += ["", "## Reviewer notes", ""]
    used = False
    for a, b in d["formal_only"] + d["informal_only"]:
        key = f"{a}->{b}"
        if key in notes:
            used = True
            lines.append(f"- `{a} -> {b}`: {notes[key]}")
    if not used:
        lines.append("- none recorded")
    lines += [
        "",
        "## Not yet mapped (informal edges with no formal counterpart)",
        "",
        f"{len(d['unmapped'])} edge(s); these blocks have no Lean declaration in "
        "`lean/declarations.json`, so no formal edge can exist yet.",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--informal", default=str(ROOT / "blocks" / "graph.json"))
    ap.add_argument("--formal", default=str(ROOT / "blocks" / "formal_graph.json"))
    ap.add_argument("--notes", default=str(ROOT / "blocks" / "discrepancy_notes.json"))
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    informal = load_edges(args.informal, DEPENDENCY_KINDS)
    formal = load_edges(args.formal)
    d = compare(informal, formal)
    notes = {}
    if Path(args.notes).exists():
        notes = json.loads(Path(args.notes).read_text(encoding="utf-8")).get("notes", {})

    if args.json:
        print(json.dumps(d, indent=2))
        return 0

    print(f"discrepancy over {len(d['universe'])} mapped block(s):")
    print(f"  agree: {len(d['agree'])}  formal-only: {len(d['formal_only'])}  "
          f"informal-only: {len(d['informal_only'])}  unmapped: {len(d['unmapped'])}")
    for a, b in d["formal_only"]:
        print(f"    formal-only: {a} -> {b}")
    for a, b in d["informal_only"]:
        print(f"    informal-only: {a} -> {b}")

    if args.report or args.check_report:
        text = render_report(d, notes)
        if args.check_report:
            actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
            if actual != text:
                print(f"discrepancy: report drift in {REPORT.relative_to(ROOT)}")
                return 1
            print("discrepancy: report current")
        else:
            REPORT.parent.mkdir(parents=True, exist_ok=True)
            REPORT.write_text(text, encoding="utf-8")
            print(f"discrepancy: wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
