#!/usr/bin/env python3
"""Frontier report (Architecture.md Section 19, "Frontier": open obligations
across the project).

Collects, from the committed records:

* blocks whose current layer status is not `pass` (or which have a `fail`);
* confirmed blocks with no Lean counterpart (no entry in `lean/declarations.json`);
* representation bridge obligations with no discharging declaration
  (`blocks/bridges.json`);
* open author decisions and journal escalations.

Renders `reports/frontier.md`; `--check-report` detects drift.

Usage:
    python3 scripts/frontier.py
    python3 scripts/frontier.py --report
    python3 scripts/frontier.py --check-report
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import decisions  # noqa: E402
import scope  # noqa: E402
import status  # noqa: E402

ROOT = HERE.parent
REPORT = ROOT / "reports" / "frontier.md"
SCOPE_STORE = ROOT / "blocks" / "scope_decisions.json"
SCOPE_ORDER = ["worth-formalizing", "deferred", "out-of-scope", "undecided"]


def load_json(rel):
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def non_pass_layers():
    registry = status.load_registry(ROOT / "blocks" / "registry.json")
    records = status.load_evidence(ROOT / "evidence")
    rep = {"encoding": status.hash_file(ROOT / "representation" / "pilot-encoding.md")}
    grouped = status.group_by_block_layer(records)
    tiers = status.load_default_tiers()
    rows = []
    for block in sorted(grouped):
        for layer, st in sorted(status.block_status(grouped[block], registry, rep,
                                                    tiers=tiers, block=block).items()):
            if st["status"] != "pass":
                rows.append((block, layer, st["status"], st["current"], st["stale"]))
    return rows


def unmapped_blocks():
    registry = status.load_registry(ROOT / "blocks" / "registry.json")
    decls = load_json("lean/declarations.json").get("blocks", {})
    return sorted(b for b, e in registry.items() if e.get("status") == "confirmed" and b not in decls)


def triage(unmapped, scopes):
    """Group unmapped blocks by scope disposition (Section 17)."""
    groups = {k: [] for k in SCOPE_ORDER}
    for block in unmapped:
        entry = scopes.get(block)
        value = entry.get("disposition") if isinstance(entry, dict) else entry
        groups[value if value in groups else "undecided"].append(block)
    return groups


def open_bridges():
    obligations = []
    for name, entry in load_json("representation/coverage.json").items():
        obligations += [(name, o) for o in entry.get("bridge_obligations", [])]
    proved = load_json("blocks/bridges.json").get("proved", {})
    return [(name, o) for name, o in obligations if o not in proved]


def render():
    rows = non_pass_layers()
    unmapped = unmapped_blocks()
    groups = triage(unmapped, scope.load(SCOPE_STORE))
    bridges = open_bridges()
    standing = decisions.load_standing(ROOT / "decisions" / "standing.json")
    escalations = decisions.open_escalations(ROOT / "journal" / "events.jsonl")
    obligations = [b for b in unmapped if b not in groups["out-of-scope"]]
    lines = [
        "# Frontier report (Section 19)",
        "",
        "Generated by `scripts/frontier.py`: open obligations across the project.",
        "",
        "## Layers not passing",
        "",
        "| block | layer | status | current | stale |",
        "|---|---|---|---|---|",
    ]
    for block, layer, st, cur, stale in rows:
        lines.append(f"| `{block}` | {layer} | {st} | {cur} | {stale} |")
    if not rows:
        lines.append("| _none_ | | | | |")
    lines += ["", "## Representation bridges still open", "", "| representation | obligation |", "|---|---|"]
    for name, o in bridges:
        lines.append(f"| `{name}` | `{o}` |")
    if not bridges:
        lines.append("| _none_ | |")
    lines += [
        "",
        f"## Unmapped blocks ({len(unmapped)})",
        "",
        "Scope triage (Sections 16.4, 17); an unrecorded block is undecided, not",
        "assumed worth formalizing.",
        "",
        "| disposition | count |",
        "|---|---|",
    ]
    for value in SCOPE_ORDER:
        lines.append(f"| {value} | {len(groups[value])} |")
    lines += [
        "",
        f"### Open obligations ({len(obligations)})",
        "",
        "Unmapped blocks not marked `out-of-scope`.",
        "",
        ", ".join(f"`{b}`" for b in obligations) if obligations else "- none",
        "",
    ]
    if groups["undecided"]:
        lines += [
            f"### Undecided ({len(groups['undecided'])})",
            "",
            "Awaiting an author scope disposition.",
            "",
            ", ".join(f"`{b}`" for b in groups["undecided"]),
            "",
        ]
    lines += ["## Open author decisions", "", "| id | category |", "|---|---|"]
    for d in standing:
        lines.append(f"| `{d['id']}` | {d['category']} |")
    for e in escalations:
        lines.append(f"| `{e.get('event_id')}` | escalation |")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    text = render()
    if args.check_report:
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != text:
            print("frontier: report drift in reports/frontier.md")
            return 1
        print("frontier: report current")
        return 0

    rows = non_pass_layers()
    print(f"frontier: {len(rows)} layer(s) not passing, "
          f"{len(open_bridges())} open bridge(s), {len(unmapped_blocks())} unmapped block(s)")
    for block, layer, st, *_ in rows:
        print(f"  {block:10s} {layer:14s} {st}")
    if args.report:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(text, encoding="utf-8")
        print("frontier: wrote reports/frontier.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
