#!/usr/bin/env python3
"""Change blast-radius / impact analysis (Architecture.md Sections 13.1, 13.2,
19 "Staleness"; P4).  Answers, before a change is accepted: if this facet
changes, which of the current evidence records become stale, and what rework
does that schedule?

The analysis is **non-destructive**: it simulates the new hash in memory and
runs the validity rule (Section 7.2), so it can be used on a proposed change
before it is made.  It never edits the registry, the manuscript, or evidence.

Two directions are reported:

* **Records:** every currently-current evidence record that lists the changed
  artifact among its computed inputs becomes stale.
* **Blocks:** the transitive downstream *users* of the changed block
  (`uses_statement` / `uses_definition`, confirmed edges), i.e. the blocks whose
  contract the change can reach.

Usage:
    python3 scripts/impact.py --artifact B-D014/informal_statement
    python3 scripts/impact.py --artifact representation/encoding
    python3 scripts/impact.py --artifact B-D014/informal_statement --report
    python3 scripts/impact.py --artifact B-D014/informal_statement --check-report
"""
from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import closure  # noqa: E402
import status  # noqa: E402

ROOT = HERE.parent
NEW_HASH = "0" * 64
DEPENDENCY_KINDS = {"uses_statement", "uses_definition"}
REPORT = ROOT / "reports" / "impact.md"


def affected_blocks(block, edges):
    """Transitive users of ``block`` (blocks whose closure reaches it)."""
    users = {}
    for e in edges:
        if e.get("kind") in DEPENDENCY_KINDS:
            users.setdefault(e["to"], set()).add(e["from"])
    seen, stack = set(), list(users.get(block, ()))
    while stack:
        cur = stack.pop()
        if cur in seen or cur == block:
            continue
        seen.add(cur)
        stack.extend(users.get(cur, ()))
    return sorted(seen)


def load_formal_edges(path):
    doc = json.loads(Path(path).read_text(encoding="utf-8"))
    return doc.get("edges", [])


def formal_dependents(block, formal_edges):
    """Transitive formal users of ``block`` (via ``formal_uses``)."""
    users = {}
    for e in formal_edges:
        users.setdefault(e["to"], set()).add(e["from"])
    seen, stack = set(), list(users.get(block, ()))
    while stack:
        cur = stack.pop()
        if cur in seen or cur == block:
            continue
        seen.add(cur)
        stack.extend(users.get(cur, ()))
    return sorted(seen)


def changed_artifacts(artifact, registry, formal_edges):
    """The set of facets whose hash a change to ``artifact`` would alter.

    A definition change (Section 13.2 class C4) propagates: a change to a
    block's ``formal_statement`` -- or to the ``formal_proof`` *body* of a
    definition -- changes the ``definition_closure`` of every formal dependent
    (Section 6), because that facet hashes the statements of the declarations
    the dependent transitively uses. A theorem's proof change (C1) does not
    propagate.
    """
    changed = {artifact}
    block, _, facet = artifact.partition("/")
    if formal_edges and facet.startswith("formal_"):
        is_definition = registry.get(block, {}).get("kind") == "definition"
        if facet == "formal_statement" or (facet == "formal_proof" and is_definition):
            for dep in formal_dependents(block, formal_edges):
                changed.add(f"{dep}/definition_closure")
    return changed


def simulate(artifact, registry, records, representation_hashes, new_hash=NEW_HASH,
             formal_edges=None):
    """Return the currently-current records that the change would stale."""
    changed = changed_artifacts(artifact, registry, formal_edges or [])
    reg2 = copy.deepcopy(registry)
    rep2 = dict(representation_hashes)
    for art in changed:
        block, _, facet = art.partition("/")
        if block == "representation":
            rep2[facet] = new_hash
            continue
        entry = reg2.setdefault(block, {}).setdefault("facets", {})
        if isinstance(entry.get(facet), dict):
            entry[facet]["hash"] = new_hash
        else:
            entry[facet] = {"hash": new_hash}
    staled = []
    for r in records:
        if not status.record_is_current(r, registry, representation_hashes):
            continue  # already stale: not this change's doing
        if not status.record_is_current(r, reg2, rep2):
            staled.append(r)
    staled.sort(key=lambda r: r.get("evidence_id", ""))
    return staled


def stale_inputs(record, artifact):
    return [i["artifact"] for i in record.get("inputs", []) if i["artifact"] == artifact]


def render_report(artifact, staled, blocks):
    lines = [
        "# Impact report (Sections 13.1, 13.2, 19)",
        "",
        "Generated by `scripts/impact.py` (`--check-report`). Non-destructive:",
        f"it simulates changing `{artifact}` and applies the validity rule to the",
        "committed evidence. Records listed as staled were *current* and list the",
        "artifact among their computed inputs; the change would schedule them for",
        "rework.",
        "",
        f"## Proposed change: `{artifact}`",
        "",
        f"- downstream blocks (transitive users): {', '.join('`'+b+'`' for b in blocks) or 'none'}",
        f"- evidence records that would go stale: {len(staled)}",
        "",
        "| record | block | layer |",
        "|---|---|---|",
    ]
    for r in staled:
        lines.append(f"| {r['evidence_id']} | `{r['block']}` | {r['layer']} |")
    if not staled:
        lines.append("| _none_ | | |")
    lines += [
        "",
        "## Not staled (by the statement/proof separation, Section 13.1)",
        "",
        "A change to a block's *statement* facet stales the review/correspondence",
        "records that list it, but not verification records (which bind only to the",
        "block's own `formal_proof`). A change to a *proof* facet stales only that",
        "block's own review/verification.",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--artifact", default="B-D014/informal_statement")
    ap.add_argument("--registry", default=str(ROOT / "blocks" / "registry.json"))
    ap.add_argument("--graph", default=str(ROOT / "blocks" / "graph.json"))
    ap.add_argument("--formal-graph", default=str(ROOT / "blocks" / "formal_graph.json"))
    ap.add_argument("--evidence-dir", default=str(ROOT / "evidence"))
    ap.add_argument("--representation", default=str(ROOT / "representation" / "pilot-encoding.md"))
    ap.add_argument("--representation-name", default="encoding")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    registry = status.load_registry(Path(args.registry))
    edges = closure.load_edges(Path(args.graph), confirmed_only=True)
    formal_edges = load_formal_edges(args.formal_graph) if Path(args.formal_graph).exists() else []
    records = status.load_evidence(args.evidence_dir)
    rep = {args.representation_name: status.hash_file(Path(args.representation))}

    block = args.artifact.split("/", 1)[0]
    blocks = affected_blocks(block, edges) if block != "representation" else []
    staled = simulate(args.artifact, registry, records, rep, formal_edges=formal_edges)

    if args.json:
        print(json.dumps({
            "artifact": args.artifact,
            "downstream_blocks": blocks,
            "staled_records": [
                {"evidence_id": r["evidence_id"], "block": r["block"], "layer": r["layer"]}
                for r in staled
            ],
        }, indent=2, sort_keys=True))
        return 0

    print(f"impact of changing {args.artifact}:")
    print(f"  downstream blocks: {len(blocks)} ({', '.join(blocks) or 'none'})")
    print(f"  records that would go stale: {len(staled)}")
    for r in staled:
        print(f"    {r['evidence_id']}  {r['block']:10s} {r['layer']}")

    if args.report or args.check_report:
        text = render_report(args.artifact, staled, blocks)
        if args.check_report:
            actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
            if actual != text:
                print(f"impact: report drift in {REPORT.relative_to(ROOT)}")
                return 1
            print("impact: report current")
        else:
            REPORT.parent.mkdir(parents=True, exist_ok=True)
            REPORT.write_text(text, encoding="utf-8")
            print(f"impact: wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
