#!/usr/bin/env python3
"""Manuscript reconciliation (Architecture.md Section 11a.5).

Formalization produces proposals to change the manuscript: a reconstructed
proof (an ``Explanation`` for a block stated without proof), a simplification, a
newly proved commented-out result, or a statement correction. This catalogue
registers them and tracks their acceptance, so the loop from Lean back to the
prose has one place to live.

A proposal is **not** an evidence record and changes no layer status. Setting a
proposal's state is author-reserved: the tool refuses ``accepted``/``rejected``
unless ``--decided-by`` begins with ``author:``. The manuscript edit itself is
performed by the author with the mandated latin1 procedure; this tool only
records the resulting manuscript hash.

Usage:
    python3 scripts/reconcile.py --sync
    python3 scripts/reconcile.py --list
    python3 scripts/reconcile.py --report
    python3 scripts/reconcile.py --check-report
    python3 scripts/reconcile.py accept R-0001 --decided-by author:session81 \
        --manuscript-hash <sha256>
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_STORE = ROOT / "reconciliation" / "proposals.json"
REPORT = ROOT / "reports" / "reconciliation.md"
KINDS = {
    "reconstructed-proof",
    "simplification",
    "newly-proven-commented-result",
    "statement-correction",
}
STATES = {"open", "accepted", "rejected", "superseded"}


def load(path=DEFAULT_STORE):
    p = Path(path)
    if not p.exists():
        return {}
    doc = json.loads(p.read_text(encoding="utf-8"))
    return doc.get("proposals", doc) if isinstance(doc, dict) else doc


def save(proposals, path=DEFAULT_STORE):
    p = Path(path)
    doc = {"note": "Formalization-produced proposals to change the manuscript "
                   "(Architecture.md Section 11a.5). Not evidence; acceptance is "
                   "author-reserved.",
           "proposals": proposals}
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(doc, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def next_id(proposals):
    mx = 0
    for pid in proposals:
        m = re.match(r"R-(\d{4})$", pid)
        if m:
            mx = max(mx, int(m.group(1)))
    return f"R-{mx + 1:04d}"


def first_line(path):
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip().lstrip("#").strip()
        if line:
            return line
    return ""


def sync_explanations(proposals, explanations_dir):
    """Register an Explanation for every block that has one, once."""
    registered = 0
    sources = {p.get("source") for p in proposals.values()}
    for path in sorted(Path(explanations_dir).glob("*.md")):
        try:
            rel = str(path.relative_to(ROOT))
        except ValueError:
            rel = path.name
        if rel in sources:
            continue
        pid = next_id(proposals)
        proposals[pid] = {
            "kind": "reconstructed-proof",
            "block": path.stem,
            "source": rel,
            "prose_change": f"Add the reconstructed proof in {rel}: {first_line(path)}",
            "state": "open",
            "decided_by": None,
            "manuscript_hash": None,
        }
        registered += 1
    return registered


def set_state(proposals, pid, state, decided_by, manuscript_hash=None, rationale=""):
    if pid not in proposals:
        return f"unknown proposal {pid}"
    if state not in STATES:
        return f"invalid state {state!r}"
    if state in ("accepted", "rejected") and not (
        decided_by and decided_by.startswith("author:")
    ):
        return "acceptance is author-reserved (--decided-by author:...)"
    entry = proposals[pid]
    entry["state"] = state
    entry["decided_by"] = decided_by
    if rationale:
        entry["rationale"] = rationale
    if manuscript_hash:
        entry["manuscript_hash"] = manuscript_hash
    if state == "accepted" and not entry.get("manuscript_hash"):
        return "acceptance requires --manuscript-hash of the edited manuscript"
    return None


def render_report(proposals):
    lines = [
        "# Manuscript reconciliation (Section 11a.5)",
        "",
        "Generated by `scripts/reconcile.py`. Formalization-produced proposals to",
        "change the manuscript. Acceptance is author-reserved; a proposal changes",
        "no layer status.",
        "",
    ]
    openp = {k: v for k, v in sorted(proposals.items()) if v.get("state") == "open"}
    lines += [f"## Open proposals ({len(openp)})", "",
              "| id | kind | block | proposed change |", "|---|---|---|---|"]
    for pid, p in openp.items():
        lines.append(
            f"| `{pid}` | {p.get('kind','')} | `{p.get('block','')}` | "
            f"{p.get('prose_change','')} |"
        )
    if not openp:
        lines.append("| _none_ | | | |")
    lines += ["", "## Resolved", "", "| id | state | block | decided by | manuscript hash |",
              "|---|---|---|---|---|"]
    resolved = {k: v for k, v in sorted(proposals.items()) if v.get("state") != "open"}
    for pid, p in resolved.items():
        lines.append(
            f"| `{pid}` | {p.get('state')} | `{p.get('block','')}` | "
            f"{p.get('decided_by') or ''} | {(p.get('manuscript_hash') or '')[:12]} |"
        )
    if not resolved:
        lines.append("| _none_ | | | | |")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--store", default=str(DEFAULT_STORE))
    ap.add_argument("--explanations", default=str(ROOT / "blocks" / "explanations"))
    ap.add_argument("--sync", action="store_true")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    sub = ap.add_subparsers(dest="cmd")
    for state in ("accept", "reject", "supersede", "reopen"):
        sp = sub.add_parser(state)
        sp.add_argument("proposal")
        sp.add_argument("--decided-by", default="")
        sp.add_argument("--manuscript-hash", default="")
        sp.add_argument("--rationale", default="")
    args = ap.parse_args(argv)

    proposals = load(args.store)

    if args.sync:
        n = sync_explanations(proposals, args.explanations)
        save(proposals, args.store)
        print(f"reconcile: registered {n} proposal(s), {len(proposals)} total")
        return 0

    if args.list:
        for pid, p in sorted(proposals.items()):
            print(f"{pid}  {p.get('state'):10s} {p.get('kind'):30s} {p.get('block','')}")
        return 0

    if args.cmd:
        state = {"accept": "accepted", "reject": "rejected",
                 "supersede": "superseded", "reopen": "open"}[args.cmd]
        err = set_state(proposals, args.proposal, state, args.decided_by,
                        args.manuscript_hash or None, args.rationale)
        if err:
            print(f"reconcile: {err}", file=sys.stderr)
            return 1
        save(proposals, args.store)
        print(f"reconcile: {args.proposal} -> {state}")
        return 0

    text = render_report(proposals)
    if args.check_report:
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != text:
            print(f"reconcile: report drift in {REPORT.relative_to(ROOT)}")
            return 1
        print("reconcile: report current")
        return 0
    if args.report:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(text, encoding="utf-8")
        print(f"reconcile: wrote {REPORT.relative_to(ROOT)}")
        return 0

    print(f"reconcile: {len(proposals)} proposal(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
