#!/usr/bin/env python3
"""Project views (Architecture.md Section 19, roadmap Phase 5).

Renders deterministic, tracked reports from the block registry, the evidence
records, and the representation coverage map:

    reports/coverage.md         status vectors per block (Section 19 Coverage)
    reports/trust_boundary.md   what verified results rest on without proof
    reports/staleness.md        what became stale and why

Only the views whose inputs already exist are rendered; the interface proper
(Sections 19, Phase 5) is deferred.  The reports are regenerable, so `--check`
detects drift the same way `ingest.py --check` does, and the gate treats a
dirty report as a failure.

Usage:
    python3 scripts/report.py
    python3 scripts/report.py --check
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))
import status  # noqa: E402
import trust  # noqa: E402

LAYER_ORDER = ["review", "correspondence", "verification", "representation"]
EMPTY = "-"


def block_status_vector(registry, records, representation_hashes, tiers=None):
    """Return {block: {layer: status}} over all blocks that have records."""
    grouped = status.group_by_block_layer(records)
    return {
        block: status.block_status(layers, registry, representation_hashes,
                                   tiers=tiers, block=block)
        for block, layers in grouped.items()
    }


def render_coverage(registry, records, coverage, boundary, vector):
    blocks_with_evidence = sorted(vector)
    lines = [
        "# Coverage report (Section 19)",
        "",
        "Generated by `scripts/report.py` from `blocks/registry.json`,",
        "`evidence/`, and `representation/coverage.json`. Do not edit by hand.",
        "",
        "## Summary",
        "",
        f"- Blocks in registry: {len(registry)}",
        f"- Blocks with any evidence: {len(blocks_with_evidence)}",
        f"- Evidence records: {len(records)}",
        f"- Representations declared: {len(coverage)}",
        "",
        "Derived block status (Section 8.2) is **not asserted** here: the",
        "workspace does not yet record contract acceptance (Draft vs",
        "Developing) or treatment tiers, so the per-layer status vector is",
        "shown instead (P8: completion is established by evidence, never by",
        "assertion).",
        "",
        "## Blocks with evidence",
        "",
        "| block | kind | section | " + " | ".join(LAYER_ORDER) + " | trust |",
        "|---|---|---|" + "---|" * (len(LAYER_ORDER) + 1),
    ]
    for block in blocks_with_evidence:
        entry = registry.get(block, {})
        layers = vector[block]
        cells = [layers.get(layer, {}).get("status", "none") for layer in LAYER_ORDER]
        residuals = trust.block_residuals(boundary.get(block, []))
        lines.append(
            "| `{block}` | {kind} | {section} | {cells} | {trust} |".format(
                block=block,
                kind=entry.get("kind", EMPTY),
                section=(entry.get("section") or EMPTY),
                cells=" | ".join(cells),
                trust="; ".join(residuals) if residuals else EMPTY,
            )
        )
    lines += [
        "",
        f"{len(registry) - len(blocks_with_evidence)} block(s) have no evidence.",
        "",
    ]
    return "\n".join(lines)


def render_trust_boundary(registry, coverage, representations, boundary, records,
                          proved_bridges=None):
    proved_bridges = set(proved_bridges or ())
    lines = [
        "# Trust boundary report (Sections 6, 7.5, 11.5)",
        "",
        "Generated by `scripts/report.py`. The trust boundary is everything",
        "verified results rest on without proof in the project: open",
        "reductions, statement-only blocks, cited external results, and",
        "non-standard axioms. A `faithful-with-caveat` representation also",
        "contributes its residuals.",
        "",
        "## Representations",
        "",
        "| name | file | record | outcome | current | residuals | covers |",
        "|---|---|---|---|---|---|---|",
    ]
    for name, rb in sorted(representations.items()):
        lines.append(
            "| `{name}` | `{file}` | {record} | {outcome} | {current} | {res} | {n} |".format(
                name=name,
                file=rb.get("file") or EMPTY,
                record=rb.get("record") or EMPTY,
                outcome=rb.get("outcome") or "unaudited",
                current="yes" if rb["current"] else "no",
                res=", ".join(rb["residuals"]) if rb["residuals"] else EMPTY,
                n=len(rb["covers"]),
            )
        )
    lines += [
        "",
        "## Residuals propagated to blocks",
        "",
        "A `faithful-with-caveat` representation imposes its residuals on every",
        "block it covers, so the compromise is visible in the block's trust",
        "boundary (Section 11.5).",
        "",
        "| block | representation | outcome | residuals |",
        "|---|---|---|---|",
    ]
    shown = 0
    for block in sorted(boundary):
        for rb in boundary[block]:
            if not rb["residuals"] and rb["outcome"] != "unfaithful":
                continue
            shown += 1
            lines.append(
                "| `{block}` | `{name}` | {outcome} | {res} |".format(
                    block=block,
                    name=rb["name"],
                    outcome=rb.get("outcome") or EMPTY,
                    res=", ".join(rb["residuals"]) if rb["residuals"] else EMPTY,
                )
            )
    if not shown:
        lines.append("| " + EMPTY + " | " + EMPTY + " | " + EMPTY + " | " + EMPTY + " |")
    lines += [
        "",
        "## Unproved bridge obligations",
        "",
        "Bridge obligations turn an encoding judgment into formal evidence",
        "(Section 7.4); until proved they sit in the trust boundary. Obligations",
        "discharged in `blocks/bridges.json` are excluded here.",
        "",
    ]
    for name, rb in sorted(representations.items()):
        obligations = [o for o in rb.get("bridge_obligations", [])
                       if o not in proved_bridges]
        if obligations:
            lines.append(f"- `{name}`: " + ", ".join(f"`{o}`" for o in obligations))
    if not any(o for rb in representations.values()
               for o in rb.get("bridge_obligations", []) if o not in proved_bridges):
        lines.append("- none open")
    lines += [
        "",
        "## Statement-only / out-of-scope",
        "",
    ]
    scoped = [
        (bid, b.get("scope")) for bid, b in sorted(registry.items()) if b.get("scope")
    ]
    if scoped:
        for bid, scope in scoped:
            lines.append(f"- `{bid}`: `{scope}`")
    else:
        lines.append(
            "No block currently declares `formalization_scope` (all "
            "`scope: null`), so there are no statement-only entries yet."
        )
    lines.append("")
    return "\n".join(lines)


def stale_inputs(record, registry, representation_hashes):
    stale = []
    for inp in record.get("inputs", []):
        current = status.resolve(inp["artifact"], registry, representation_hashes)
        if current is None:
            stale.append(f"{inp['artifact']}: unresolved")
        elif current != inp["hash"]:
            stale.append(
                f"{inp['artifact']}: recorded {inp['hash'][:12]}... "
                f"now {current[:12]}..."
            )
    return stale


def render_staleness(registry, records, representation_hashes):
    lines = [
        "# Staleness report (Sections 7.2, 8)",
        "",
        "Generated by `scripts/report.py`. A record is current iff every input",
        "hash equals the artifact's current hash; otherwise it is stale. Stale",
        "evidence is not false: it remains a true statement about the recorded",
        "inputs, but it is no longer evidence about the current block. A stale",
        "record is **superseded** when a current record names it through",
        "`supersedes`; otherwise it is **awaiting** re-audit. Only awaiting",
        "records represent outstanding work.",
        "",
    ]
    stale = []
    for r in sorted(records, key=lambda r: r.get("evidence_id", "")):
        if not status.record_is_current(r, registry, representation_hashes):
            stale.append(r)
    if not stale:
        lines += [
            f"No stale records: all {len(records)} record(s) are current.",
            "",
        ]
        return "\n".join(lines)
    superseded_ids = status.superseded_ids(records, registry, representation_hashes)
    awaiting = [r for r in stale if r.get("evidence_id") not in superseded_ids]
    lines += [
        f"{len(stale)} of {len(records)} record(s) are stale "
        f"({len(stale) - len(awaiting)} superseded, {len(awaiting)} awaiting):",
        "",
        "| record | block | layer | class | stale inputs |",
        "|---|---|---|---|---|",
    ]
    for r in stale:
        details = stale_inputs(r, registry, representation_hashes)
        klass = "superseded" if r.get("evidence_id") in superseded_ids else "awaiting"
        lines.append(
            "| {id} | `{block}` | {layer} | {klass} | {details} |".format(
                id=r.get("evidence_id", EMPTY),
                block=r.get("block", EMPTY),
                layer=r.get("layer", EMPTY),
                klass=klass,
                details="<br>".join(details),
            )
        )
    lines.append("")
    return "\n".join(lines)


def build(root: Path, representation_path=None, representation_name="encoding"):
    registry = status.load_registry(root / "blocks" / "registry.json")
    records = status.load_evidence(root / "evidence")
    coverage = trust.load_coverage(root / "representation" / "coverage.json")
    rep = {}
    if representation_path:
        rep[representation_name] = trust.hash_file(root / representation_path)
    representations, boundary = trust.compute(registry, coverage, records, rep)
    bridges_path = root / "blocks" / "bridges.json"
    proved_bridges = []
    if bridges_path.exists():
        proved_bridges = list(
            json.loads(bridges_path.read_text(encoding="utf-8")).get("proved", {})
        )
    vector = block_status_vector(registry, records, rep, tiers=status.load_default_tiers())
    return {
        "reports/coverage.md": render_coverage(
            registry, records, coverage, boundary, vector
        ),
        "reports/trust_boundary.md": render_trust_boundary(
            registry, coverage, representations, boundary, records, proved_bridges
        ),
        "reports/staleness.md": render_staleness(registry, records, rep),
    }


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--root", default=None)
    ap.add_argument("--representation", default="representation/pilot-encoding.md")
    ap.add_argument("--representation-name", default="encoding")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    root = Path(args.root).resolve() if args.root else HERE.parent
    representation_path = args.representation
    rendered = build(root, representation_path, args.representation_name)

    if args.check:
        drift = []
        for rel, text in sorted(rendered.items()):
            path = root / rel
            existing = path.read_text(encoding="utf-8") if path.exists() else None
            if existing != text:
                drift.append(rel)
        if drift:
            for rel in drift:
                print(f"report drift: {rel}")
            return 1
        print(f"report: {len(rendered)} view(s) current")
        return 0

    for rel, text in sorted(rendered.items()):
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
