#!/usr/bin/env python3
"""Formal sanity checks report (Architecture.md Section 11.3).

Verifies that each sanity declaration named in `blocks/sanity.json` is present
in `lean/Mslang/Sanity.lean`, and renders `reports/sanity.md`.  The checks
themselves (non-vacuity, definition examples, negation probes, convention
checks) are Lean declarations; `lake build` is what actually runs them.

Usage:
    python3 scripts/sanity.py
    python3 scripts/sanity.py --report
    python3 scripts/sanity.py --check-report
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "blocks" / "sanity.json"
SOURCE = ROOT / "lean" / "Mslang" / "Sanity.lean"
REPORT = ROOT / "reports" / "sanity.md"


def load_checks(path):
    return json.loads(Path(path).read_text(encoding="utf-8")).get("checks", [])


def missing_declarations(checks, source):
    text = Path(source).read_text(encoding="utf-8")
    missing = []
    for c in checks:
        name = c["decl"]
        if not re.search(r"(?m)^(theorem|example|def|lemma)\s+" + re.escape(name) + r"\b", text):
            missing.append(name)
    return missing


def render_report(checks):
    lines = [
        "# Formal sanity checks (Section 11.3)",
        "",
        "Generated by `scripts/sanity.py`. Declarations live in",
        "`lean/Mslang/Sanity.lean`; `lake build` runs them. Read-back alone can",
        "miss a formal statement that *reads* correctly but means something",
        "degenerate, so each audited block also carries lightweight checks.",
        "",
        "| block | kind | declaration | note |",
        "|---|---|---|---|",
    ]
    for c in checks:
        lines.append(f"| `{c['block']}` | {c['kind']} | `{c['decl']}` | {c['note']} |")
    lines.append("")
    return "\n".join(lines)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    ap.add_argument("--config", default=str(CONFIG))
    ap.add_argument("--source", default=str(SOURCE))
    ap.add_argument("--report", action="store_true")
    ap.add_argument("--check-report", action="store_true")
    args = ap.parse_args(argv)

    checks = load_checks(args.config)
    missing = missing_declarations(checks, args.source)
    if missing:
        for m in missing:
            print(f"sanity: missing declaration {m!r} in {args.source}", file=sys.stderr)
        return 1

    text = render_report(checks)
    print(f"sanity: {len(checks)} check(s), all declarations present")

    if args.check_report:
        actual = REPORT.read_text(encoding="utf-8") if REPORT.exists() else None
        if actual != text:
            print("sanity: report drift in reports/sanity.md")
            return 1
        print("sanity: report current")
        return 0
    if args.report:
        REPORT.parent.mkdir(parents=True, exist_ok=True)
        REPORT.write_text(text, encoding="utf-8")
        print("sanity: wrote reports/sanity.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
