import Mslang.Congruence

/-!
`B-D035`/`B-D036`: elementary translations and translations of a `Σ`-algebra.

A `t`-elementary translation of sort `s` for `A` is a map `A_t → A_s` obtained
by filling every argument of a formal operation `σ ∈ Σ_{w,s}` with constants
except the `i`-th position, which is the variable `x`. A `t`-translation of sort
`s` is a finite composite of elementary translations, with the identity counted
as a translation.
-/

universe u

namespace Mslang

variable {S : Type u}

/-- `B-D035`: `T : A_t → A_s` is a `t`-elementary translation of sort `s` for
`A` when it is obtained from an operation `σ ∈ Σ_{w,s}`, an index `i < |w|`
with `w_i = t`, and constants in all the other positions: for every `x ∈ A_t`,
`T(x) = F_σ(…, x, …)` with `x` in position `i`. The nonemptiness of `w` is
witnessed by `i : Fin w.length`. -/
def IsElemTranslation (Sig : Signature S) (A : Alg Sig) (t s : S)
    (T : A.1 t → A.1 s) : Prop :=
  ∃ (w : List S) (i : Fin w.length) (hwit : w.get i = t) (σ : Sig (w, s))
      (a : ∀ k : Fin w.length, k ≠ i → A.1 (w.get k)),
    ∀ x : A.1 t,
      T x = A.2 (w, s) σ (fun k =>
        if h : k = i then
          (congrArg A.1 ((congrArg (fun j : Fin w.length => w.get j) h).trans hwit)).symm ▸ x
        else a k h)

/-- `B-D035`: the `t`-elementary translations of `A`, sorted by coarity — the
subset `(Etl_t(A)_s)_{s∈S}` of `(Hom(A_t, A_s))_{s∈S}`. -/
def Etl (Sig : Signature S) (A : Alg Sig) (t : S) :
    Sub (fun s => A.1 t → A.1 s) :=
  fun s T => IsElemTranslation Sig A t s T

/-- `B-D036`: the family of `t`-translations of sort `s`, generated by the
elementary translations and closed under composition, with the identity as the
length-one composite. -/
inductive TlGen (Sig : Signature S) (A : Alg Sig) :
    (t s : S) → (A.1 t → A.1 s) → Prop where
  /-- The identity `id_{A_t}` is a `t`-translation of sort `t`. -/
  | refl (t : S) : TlGen Sig A t t id
  /-- Every `t`-elementary translation of sort `s` is a translation. -/
  | elem {t s : S} {T : A.1 t → A.1 s} :
      IsElemTranslation Sig A t s T → TlGen Sig A t s T
  /-- Translating twice in a row is translating (composition of the chain). -/
  | comp {t u s : S} {T : A.1 t → A.1 u} {U : A.1 u → A.1 s} :
      TlGen Sig A t u T → TlGen Sig A u s U → TlGen Sig A t s (U ∘ T)

/-- `B-D036`: the `t`-translations of `A`, sorted by coarity — the subset
`(Tl_t(A)_s)_{s∈S}` of `(Hom(A_t, A_s))_{s∈S}`. -/
def Tl (Sig : Signature S) (A : Alg Sig) (t : S) :
    Sub (fun s => A.1 t → A.1 s) :=
  fun s T => TlGen Sig A t s T

/-- The `S`-sorted subset concentrated at sort `s`: `Y` at `s`, empty elsewhere
(the subset-level counterpart of `deltaT`; used by `B-D037`). -/
noncomputable def deltaSub {S : Type u} {A : SSet S} (s : S) (Y : Set (A s)) :
    Sub A :=
  by classical exact Function.update (fun u => (∅ : Set (A u))) s Y

/-- `B-D037`(1): `T[L] = δ^{s, T[L_t]}` — the direct image of `L` under `T`,
concentrated at the coarity sort `s`. -/
noncomputable def transImage {S : Type u} {A : SSet S} {t s : S}
    (T : A t → A s) (L : Sub A) : Sub A :=
  deltaSub s (Set.image T (L t))

/-- `B-D037`(2): `T⁻¹[L] = δ^{t, T⁻¹[L_s]}` — the inverse image of `L` under
`T`, concentrated at the domain sort `t`. -/
noncomputable def transPreimage {S : Type u} {A : SSet S} {t s : S}
    (T : A t → A s) (L : Sub A) : Sub A :=
  deltaSub t (Set.preimage T (L s))

/-- `B-D037`(3): `T[X] = T[δ^{t,X}]`. -/
noncomputable def transImageSet {S : Type u} {A : SSet S} {t s : S}
    (T : A t → A s) (X : Set (A t)) : Sub A :=
  transImage T (deltaSub t X)

/-- `B-D037`(4): `T⁻¹[Y] = T⁻¹[δ^{s,Y}]`. -/
noncomputable def transPreimageSet {S : Type u} {A : SSet S} {t s : S}
    (T : A t → A s) (Y : Set (A s)) : Sub A :=
  transPreimage T (deltaSub s Y)

/-- `B-D038`: the congruence `Ω^A(L)` *cogenerated* by `L` (the syntactic
congruence) — `x, y ∈ A_t` are related when every `t`-translation `T` of any
sort `s` cannot distinguish them against `L`. -/
@[instance_reducible]
def congCogenerated (Sig : Signature S) (A : Alg Sig) (L : Sub A.1) :
    SortedEqv A.1 :=
  fun t =>
    ⟨fun x y => ∀ (s : S) (T : A.1 t → A.1 s),
        TlGen Sig A t s T → (T x ∈ L s ↔ T y ∈ L s),
     ⟨fun _ => fun _ _ _ => Iff.rfl,
      fun h => fun s T hT => (h s T hT).symm,
      fun h1 h2 => fun s T hT => (h1 s T hT).trans (h2 s T hT)⟩⟩

/-! ### `B-P021` (`CharacCong`): congruence ⟺ `Etl`-closed ⟺ `Tl`-closed. -/

/-- The word tuple obtained from `z` at position `i` and the constants `c`
elsewhere, with `z` viewed at the `i`-th sort through `hwit : w.get i = t`
(the insertion used by `IsElemTranslation`). -/
def insertTuple {S : Type u} {A : SSet S} {w : List S} (i : Fin w.length) {t : S}
    (hwit : w.get i = t) (z : A t) (c : ∀ k : Fin w.length, k ≠ i → A (w.get k)) :
    wordProd A w :=
  fun k =>
    if h : k = i then
      (congrArg A ((congrArg (fun j : Fin w.length => w.get j) h).trans hwit)).symm ▸ z
    else c k h

/-- `IsElemTranslation` restated with `insertTuple`. -/
theorem isElemTranslation_insert {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (t s : S) (T : A.1 t → A.1 s) :
    IsElemTranslation Sig A t s T ↔
      ∃ (w : List S) (i : Fin w.length) (hwit : w.get i = t) (σ : Sig (w, s))
        (c : ∀ k : Fin w.length, k ≠ i → A.1 (w.get k)),
        ∀ z : A.1 t, T z = A.2 (w, s) σ (insertTuple i hwit z c) := by
  constructor
  · rintro ⟨w, i, hwit, σ, c, h⟩
    exact ⟨w, i, hwit, σ, c, h⟩
  · rintro ⟨w, i, hwit, σ, c, h⟩
    exact ⟨w, i, hwit, σ, c, h⟩

/-- Transporting a `Φ`-related pair of elements along an equality of sorts. -/
theorem cast_rel {S : Type u} {A : SSet S} (Φ : SortedEqv A) {s t : S} (e : s = t)
    {x y : A t} (h : (Φ t).r x y) :
    (Φ s).r ((congrArg A e).symm ▸ x) ((congrArg A e).symm ▸ y) := by
  subst e
  simpa using h

/-- `B-P021`(2): `Φ` is closed under the elementary translations of `A`. -/
def ClosesUnderEtl (Sig : Signature S) (A : Alg Sig) (Φ : SortedEqv A.1) : Prop :=
  ∀ (t s : S) (x y : A.1 t) (T : A.1 t → A.1 s),
    IsElemTranslation Sig A t s T → (Φ t).r x y → (Φ s).r (T x) (T y)

/-- `B-P021`(3): `Φ` is closed under the translations of `A`. -/
def ClosesUnderTl (Sig : Signature S) (A : Alg Sig) (Φ : SortedEqv A.1) : Prop :=
  ∀ (t s : S) (T : A.1 t → A.1 s), TlGen Sig A t s T →
    ∀ x y : A.1 t, (Φ t).r x y → (Φ s).r (T x) (T y)

/-- `B-P021`, (3) implies (2): every elementary translation is a translation. -/
theorem closesUnderEtl_of_closesUnderTl {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {Φ : SortedEqv A.1} (h : ClosesUnderTl Sig A Φ) :
    ClosesUnderEtl Sig A Φ :=
  fun t s x y T hT hxy => h t s T (.elem hT) x y hxy

/-- `B-P021`, (2) implies (3): closure under elementary translations is closed
under composition (induction on the translation). -/
theorem closesUnderTl_of_closesUnderEtl {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {Φ : SortedEqv A.1} (h : ClosesUnderEtl Sig A Φ) :
    ClosesUnderTl Sig A Φ := by
  intro t s T hT
  induction hT with
  | refl _ => intro x y hxy; exact hxy
  | elem hE => intro x y hxy; exact h _ _ x y _ hE hxy
  | comp hT hU ihT ihU => intro x y hxy; exact ihU _ _ (ihT x y hxy)

/-- `B-P021`, (1) implies (2): a congruence is closed under elementary
translations (the operation applied to the inserted arguments). -/
theorem closesUnderEtl_of_isCongruence {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {Φ : SortedEqv A.1} (h : IsCongruence Sig A.2 Φ) :
    ClosesUnderEtl Sig A Φ := by
  intro t s x y T hT hxy
  obtain ⟨w, i, hwit, σ, c, hform⟩ := (isElemTranslation_insert Sig A t s T).mp hT
  have huv : ∀ k : Fin w.length,
      (Φ (w.get k)).r (insertTuple i hwit x c k) (insertTuple i hwit y c k) := by
    intro k
    by_cases hk : k = i
    · have e : w.get k = t := (congrArg (fun j : Fin w.length => w.get j) hk).trans hwit
      have hcast : (Φ (w.get k)).r ((congrArg A.1 e).symm ▸ x) ((congrArg A.1 e).symm ▸ y) :=
        cast_rel Φ e hxy
      simpa only [insertTuple, dif_pos hk] using hcast
    · simpa only [insertTuple, dif_neg hk] using (Φ (w.get k)).refl (c k hk)
  have hcong := h (w, s) σ (insertTuple i hwit x c) (insertTuple i hwit y c) huv
  rwa [← hform x, ← hform y] at hcong

/-- The tuple with `b` in the first `j` positions and `a` in the remaining ones
(used for the telescoping in `B-P021`). -/
def mixedTuple {S : Type u} {A : SSet S} {w : List S} (a b : wordProd A w)
    (j : Fin (w.length + 1)) : wordProd A w :=
  fun k => if (k : ℕ) < (j : ℕ) then b k else a k

theorem mixedTuple_zero {S : Type u} {A : SSet S} {w : List S} (a b : wordProd A w) :
    mixedTuple a b 0 = a := by
  funext k
  simp [mixedTuple]

theorem mixedTuple_last {S : Type u} {A : SSet S} {w : List S} (a b : wordProd A w) :
    mixedTuple a b (Fin.last w.length) = b := by
  funext k
  change (if (k : ℕ) < w.length then b k else a k) = b k
  rw [if_pos k.isLt]

/-- `B-P021`, (2) implies (1): closure under elementary translations makes `Φ`
a congruence. The argument telescopes along the word: replacing the arguments of
`F_σ` one position at a time, each step being an elementary translation. -/
theorem congruence_of_closesUnderEtl {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {Φ : SortedEqv A.1} (h : ClosesUnderEtl Sig A Φ) :
    IsCongruence Sig A.2 Φ := by
  rintro ⟨w, s⟩ σ a b hab
  have h0 : mixedTuple a b 0 = a := mixedTuple_zero a b
  have hn : mixedTuple a b (Fin.last w.length) = b := mixedTuple_last a b
  have step : ∀ j : Fin w.length,
      (Φ s).r (A.2 (w, s) σ (mixedTuple a b (Fin.castSucc j)))
              (A.2 (w, s) σ (mixedTuple a b (Fin.succ j))) := by
    intro j
    let c : ∀ k : Fin w.length, k ≠ j → A.1 (w.get k) :=
      fun k _ => mixedTuple a b (Fin.castSucc j) k
    let Tj : A.1 (w.get j) → A.1 s :=
      fun z => A.2 (w, s) σ (insertTuple j rfl z c)
    have hTj : IsElemTranslation Sig A (w.get j) s Tj :=
      (isElemTranslation_insert Sig A (w.get j) s Tj).mpr
        ⟨w, j, rfl, σ, c, fun z => rfl⟩
    have hrel : (Φ (w.get j)).r (mixedTuple a b (Fin.castSucc j) j) (b j) := by
      have hj : mixedTuple a b (Fin.castSucc j) j = a j := by simp [mixedTuple]
      rw [hj]; exact hab j
    have hstep := h (w.get j) s (mixedTuple a b (Fin.castSucc j) j) (b j) Tj hTj hrel
    have htup1 : insertTuple j rfl (mixedTuple a b (Fin.castSucc j) j) c
        = mixedTuple a b (Fin.castSucc j) := by
      funext k
      by_cases hk : k = j
      · subst hk
        simp [insertTuple, mixedTuple]
      · rw [insertTuple, dif_neg hk]
    have e1 : Tj (mixedTuple a b (Fin.castSucc j) j)
        = A.2 (w, s) σ (mixedTuple a b (Fin.castSucc j)) :=
      congrArg (fun tup : wordProd A.1 w => A.2 (w, s) σ tup) htup1
    have htup2 : insertTuple j rfl (b j) c = mixedTuple a b (Fin.succ j) := by
      funext k
      by_cases hk : k = j
      · subst hk
        simp [insertTuple, mixedTuple]
      · rw [insertTuple, dif_neg hk]
        change mixedTuple a b (Fin.castSucc j) k = mixedTuple a b (Fin.succ j) k
        have h1 : ((Fin.castSucc j : Fin (w.length + 1)) : ℕ) = (j : ℕ) := rfl
        have h2 : ((Fin.succ j : Fin (w.length + 1)) : ℕ) = (j : ℕ) + 1 := rfl
        simp only [mixedTuple, h1, h2]
        by_cases hlt : (k : ℕ) < (j : ℕ)
        · rw [if_pos hlt, if_pos (by omega)]
        · have hne : (k : ℕ) ≠ (j : ℕ) := by intro hh; exact hk (Fin.ext hh)
          rw [if_neg hlt, if_neg (by omega)]
    have e2 : Tj (b j) = A.2 (w, s) σ (mixedTuple a b (Fin.succ j)) :=
      congrArg (fun tup : wordProd A.1 w => A.2 (w, s) σ tup) htup2
    rw [e1, e2] at hstep
    exact hstep
  have chain : (Φ s).r (A.2 (w, s) σ (mixedTuple a b 0))
      (A.2 (w, s) σ (mixedTuple a b (Fin.last w.length))) :=
    Fin.induction
      (motive := fun j => (Φ s).r (A.2 (w, s) σ (mixedTuple a b 0))
        (A.2 (w, s) σ (mixedTuple a b j)))
      ((Φ s).refl _) (fun j ih => (Φ s).trans ih (step j)) (Fin.last w.length)
  rwa [h0, hn] at chain

/-- `B-P021`(1) ⟺ (2). -/
theorem isCongruence_iff_closesUnderEtl {S : Type u} (Sig : Signature S)
    (A : Alg Sig) (Φ : SortedEqv A.1) :
    IsCongruence Sig A.2 Φ ↔ ClosesUnderEtl Sig A Φ :=
  ⟨closesUnderEtl_of_isCongruence Sig A, congruence_of_closesUnderEtl Sig A⟩

/-- `B-P021`(2) ⟺ (3). -/
theorem closesUnderEtl_iff_closesUnderTl {S : Type u} (Sig : Signature S)
    (A : Alg Sig) (Φ : SortedEqv A.1) :
    ClosesUnderEtl Sig A Φ ↔ ClosesUnderTl Sig A Φ :=
  ⟨closesUnderTl_of_closesUnderEtl Sig A, closesUnderEtl_of_closesUnderTl Sig A⟩

/-! ### `B-P022` (`CharacCogenCong`): `Ω^A(L)` is the greatest congruence
saturating `L`. -/

/-- `Ker(ch^L)`: the kernel of the characteristic map of `L` — two elements are
related when they lie in `L` on the same side. -/
@[instance_reducible]
def charEqv {S : Type u} {A : SSet S} (L : Sub A) : SortedEqv A :=
  fun s =>
    ⟨fun x y => x ∈ L s ↔ y ∈ L s,
     ⟨fun _ => Iff.rfl, fun h => h.symm, fun h1 h2 => h1.trans h2⟩⟩

/-- `B-P022`(1): `Ω^A(L)` is a congruence on `A`. Every composite `U ∘ T` of
translations is again a translation, which is exactly what closure under `Tl`
requires. -/
theorem congCogenerated_isCongruence {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (L : Sub A.1) : IsCongruence Sig A.2 (congCogenerated Sig A L) := by
  refine (isCongruence_iff_closesUnderEtl Sig A (congCogenerated Sig A L)).mpr
    (closesUnderEtl_of_closesUnderTl Sig A ?_)
  intro t s T hT x y hxy u U hU
  exact hxy u (U ∘ T) (.comp hT hU)

/-- `B-P022`(2): `Ω^A(L) ⊆ Ker(ch^L)` (using the identity translation). -/
theorem congCogenerated_le_charEqv {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (L : Sub A.1) : sortedEqvLe (congCogenerated Sig A L) (charEqv L) := by
  intro t x y hxy
  exact hxy t id (.refl t)

/-- `B-P022`(3): every congruence contained in `Ker(ch^L)` is contained in
`Ω^A(L)`; hence `Ω^A(L)` is the greatest congruence saturating `L`. -/
theorem le_congCogenerated_of_isCongruence {S : Type u} (Sig : Signature S)
    (A : Alg Sig) (L : Sub A.1) {Φ : SortedEqv A.1}
    (hΦ : IsCongruence Sig A.2 Φ) (h : sortedEqvLe Φ (charEqv L)) :
    sortedEqvLe Φ (congCogenerated Sig A L) := by
  intro t x y hxy s T hT
  have htl : ClosesUnderTl Sig A Φ :=
    closesUnderTl_of_closesUnderEtl Sig A (closesUnderEtl_of_isCongruence Sig A hΦ)
  exact h s (T x) (T y) (htl t s T hT x y hxy)

/-- `B-D039`: the congruence `Ω^A(L)` cogenerated by `L` is also called the
*syntactic* congruence determined by `L`. -/
abbrev syntacticCongruence {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (L : Sub A.1) : SortedEqv A.1 :=
  congCogenerated Sig A L

/-! ### `B-R018`: the category of translations and the endomorphism monoid. -/

/-- `B-R018`: the hom-set `Tl_t(A)_s` of the category `Tl(A)`, the translations
`A_t → A_s` (a subtype of the functions `A_t → A_s`). -/
def TlHom (Sig : Signature S) (A : Alg Sig) (t s : S) : Type u :=
  {T : A.1 t → A.1 s // TlGen Sig A t s T}

/-- `B-R018`: the identity morphism `id_{A_t} : t → t`, i.e. the identity
translation. -/
def TlId (Sig : Signature S) (A : Alg Sig) (t : S) : TlHom Sig A t t :=
  ⟨id, TlGen.refl t⟩

/-- `B-R018`: composition of translations, the composition of the category
`Tl(A)`; closure under composition is `TlGen.comp`. -/
def TlComp (Sig : Signature S) (A : Alg Sig) {t s u : S}
    (f : TlHom Sig A t s) (g : TlHom Sig A s u) : TlHom Sig A t u :=
  ⟨g.1 ∘ f.1, TlGen.comp f.2 g.2⟩

/-- `B-R018`: the left identity law of the category `Tl(A)`. -/
theorem TlComp_id_left (Sig : Signature S) (A : Alg Sig) {t s : S}
    (f : TlHom Sig A t s) : TlComp Sig A (TlId Sig A t) f = f :=
  Subtype.ext (funext fun _ => rfl)

/-- `B-R018`: the right identity law of the category `Tl(A)`. -/
theorem TlComp_id_right (Sig : Signature S) (A : Alg Sig) {t s : S}
    (f : TlHom Sig A t s) : TlComp Sig A f (TlId Sig A s) = f :=
  Subtype.ext (funext fun _ => rfl)

/-- `B-R018`: associativity of composition in the category `Tl(A)`. -/
theorem TlComp_assoc (Sig : Signature S) (A : Alg Sig) {t s u v : S}
    (f : TlHom Sig A t s) (g : TlHom Sig A s u) (h : TlHom Sig A u v) :
    TlComp Sig A (TlComp Sig A f g) h = TlComp Sig A f (TlComp Sig A g h) :=
  Subtype.ext (funext fun _ => rfl)

/-- `B-R018`: the endomorphisms `End_{Tl(A)}(t) = Tl_t(A)_t` form a monoid under
composition. -/
@[instance_reducible]
def tlEndMonoid (Sig : Signature S) (A : Alg Sig) (t : S) :
    Monoid (TlHom Sig A t t) where
  mul f g := TlComp Sig A f g
  one := TlId Sig A t
  mul_assoc f g h := TlComp_assoc Sig A f g h
  one_mul f := TlComp_id_left Sig A f
  mul_one f := TlComp_id_right Sig A f

attribute [instance] tlEndMonoid

/-! ### `B-P023`: saturation by `Φ` versus containment in `Ω^A(L)`. -/

/-- `L` is `Φ`-saturated exactly when `Φ` is contained in `Ker(ch^L)`. -/
theorem isSat_iff_sortedEqvLe_charEqv {S : Type u} {A : SSet S} (Φ : SortedEqv A)
    (L : Sub A) : IsSat Φ L ↔ sortedEqvLe Φ (charEqv L) := by
  constructor
  · intro h s x y hxy
    constructor
    · intro hxl
      exact h ▸ (⟨x, hxl, hxy⟩ : y ∈ sat Φ L s)
    · intro hyl
      exact h ▸ (⟨y, hyl, (Φ s).symm hxy⟩ : x ∈ sat Φ L s)
  · intro h
    funext s
    ext a
    constructor
    · rintro ⟨x, hx, hxa⟩
      exact (h s x a hxa).mp hx
    · intro ha
      exact ⟨a, ha, (Φ s).refl a⟩

/-- `B-P023` (`CharacSatCCog`): `L = [L]^Φ` iff `Φ ⊆ Ω^A(L)`. -/
theorem isSat_iff_le_congCogenerated {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (L : Sub A.1) {Φ : SortedEqv A.1} (hΦ : IsCongruence Sig A.2 Φ) :
    IsSat Φ L ↔ sortedEqvLe Φ (congCogenerated Sig A L) := by
  rw [isSat_iff_sortedEqvLe_charEqv]
  exact ⟨fun h => le_congCogenerated_of_isCongruence Sig A L hΦ h,
    fun h s x y hxy => congCogenerated_le_charEqv Sig A L s x y (h s x y hxy)⟩

/-! ### `B-P025`: `Ω^A(L) = Ω^A(∁_A L)`. -/

/-- `B-P025` (`Compl`): the congruence cogenerated by `L` is the one cogenerated
by the complement `∁_A L` (membership and non-membership are interchanged in
every clause). -/
theorem congCogenerated_compl {S : Type u} (Sig : Signature S) (A : Alg Sig)
    (L : Sub A.1) :
    congCogenerated Sig A L = congCogenerated Sig A (complA L) := by
  funext t
  apply Setoid.ext
  intro x y
  constructor
  · intro h s T hT
    have h' := h s T hT
    rw [complA_bridge, complA_bridge]
    exact h'.not
  · intro h s T hT
    have h' := h s T hT
    rw [complA_bridge, complA_bridge] at h'
    simpa only [not_not] using h'.not

/-! ### `B-P026`: intersections of cogenerated congruences. -/

/-- A componentwise meet of congruences is a congruence. -/
theorem isCongruence_iInf {S : Type u} (Sig : Signature S) {A : SSet S}
    (F : AlgStruct Sig A) {ι : Type u} (Φ : ι → SortedEqv A)
    (h : ∀ i, IsCongruence Sig F (Φ i)) :
    IsCongruence Sig F (sortedEqv_iInf Φ) := by
  intro p σ a b hab
  exact fun i => h i p σ a b (fun j => hab j i)

/-- `B-P026` (`InterCCog and CCogInter`): `⋂_j Ω^A(L^j) ⊆ Ω^A(⋂_j L^j)`. -/
theorem congCogenerated_iInter_le {S : Type u} (Sig : Signature S) (A : Alg Sig)
    {ι : Type u} (L : ι → Sub A.1) :
    sortedEqvLe (sortedEqv_iInf (fun j => congCogenerated Sig A (L j)))
      (congCogenerated Sig A (fun s => ⋂ j, L j s)) := by
  have hchar : sortedEqvLe (sortedEqv_iInf (fun j => congCogenerated Sig A (L j)))
      (charEqv (fun s => ⋂ j, L j s)) := by
    intro s x y h
    change x ∈ (⋂ j, L j s) ↔ y ∈ (⋂ j, L j s)
    rw [Set.mem_iInter, Set.mem_iInter]
    constructor
    · intro hx j
      exact (congCogenerated_le_charEqv Sig A (L j) s x y (h j)).mp (hx j)
    · intro hy j
      exact (congCogenerated_le_charEqv Sig A (L j) s x y (h j)).mpr (hy j)
  have hcong : IsCongruence Sig A.2
      (sortedEqv_iInf (fun j => congCogenerated Sig A (L j))) :=
    isCongruence_iInf Sig A.2 (fun j => congCogenerated Sig A (L j))
      (fun j => congCogenerated_isCongruence Sig A (L j))
  exact le_congCogenerated_of_isCongruence Sig A (fun s => ⋂ j, L j s) hcong hchar

/-! ### `B-P027`: `Ω^A(L) ⊆ Ω^A(T⁻¹[L])`. -/

/-- `B-P027` (`TAntiTrans`): for a translation `T ∈ Tl_t(A)_s`, the congruence
cogenerated by `L` refines the one cogenerated by the inverse image `T⁻¹[L]`. -/
theorem congCogenerated_le_transPreimage {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {t s : S} {T : A.1 t → A.1 s} (hT : TlGen Sig A t s T)
    (L : Sub A.1) :
    sortedEqvLe (congCogenerated Sig A L)
      (congCogenerated Sig A (transPreimage T L)) := by
  classical
  intro t' x y hxy s'' V hV
  by_cases hs : s'' = t
  · subst hs
    have hmem : (transPreimage T L) s'' = Set.preimage T (L s) := by
      simp [transPreimage, deltaSub, Function.update_self]
    rw [hmem, Set.mem_preimage, Set.mem_preimage]
    exact hxy s (T ∘ V) (TlGen.comp hV hT)
  · have hmem : (transPreimage T L) s'' = ∅ := by
      simp [transPreimage, deltaSub, Function.update_of_ne hs]
    rw [hmem]
    simp

/-! ### `B-R020`: `Δ^A = ⋂ Ω^A(δ^{s,a})`. -/

/-- `Δ^A`: the diagonal (equality) sorted equivalence. -/
@[instance_reducible]
def deltaEqv {S : Type u} (A : SSet S) : SortedEqv A :=
  fun _ =>
    ⟨fun x y => x = y,
     ⟨fun _ => rfl, fun h => h.symm, fun h1 h2 => h1.trans h2⟩⟩

/-- `B-R020`: the diagonal congruence `Δ^A` is the meet of the congruences
cogenerated by the Kronecker deltas `δ^{s,a}` (`{a}` at sort `s`, empty
elsewhere). A single `Ω^A(δ^{s,x})` with the identity translation already forces
`y = x`. -/
theorem deltaEqv_eq_iInf_congCogenerated {S : Type u} (Sig : Signature S)
    (A : Alg Sig) :
    deltaEqv A.1
      = sortedEqv_iInf (fun p : Sigma A.1 => congCogenerated Sig A (deltaSub p.1 {p.2})) := by
  classical
  funext s
  apply Setoid.ext
  intro x y
  constructor
  · intro h p s' T hT
    subst h
    rfl
  · intro h
    have hx : x ∈ deltaSub s ({x} : Set (A.1 s)) s := by
      simp [deltaSub, Function.update_self]
    have h2 := (h ⟨s, x⟩ s id (TlGen.refl s)).mp hx
    have hy : y = x := by
      simpa [deltaSub, Function.update_self] using h2
    exact hy.symm

/-! ### `B-P024`: `Φ = ⋂ Ω^A(δ^{s,[a]_Φ})`. -/

/-- `B-P024`
(`RepCongInterCCogKroneckerDelta`): a congruence `Φ` is the meet, over all sorts
`s` and `a : A_s`, of the congruences cogenerated by the Kronecker deltas
`δ^{s,[a]_{Φ_s}}` on the `Φ_s`-classes. -/
theorem isCongruence_eq_iInf_congCogenerated {S : Type u} (Sig : Signature S)
    (A : Alg Sig) {Φ : SortedEqv A.1} (hΦ : IsCongruence Sig A.2 Φ) :
    Φ = sortedEqv_iInf (fun p : Sigma A.1 =>
      congCogenerated Sig A (deltaSub p.1 (eqvClass Φ p.1 p.2))) := by
  classical
  have htl : ClosesUnderTl Sig A Φ :=
    closesUnderTl_of_closesUnderEtl Sig A (closesUnderEtl_of_isCongruence Sig A hΦ)
  funext t
  apply Setoid.ext
  intro x y
  constructor
  · intro hxy p s' T hT
    by_cases hs : s' = p.1
    · subst hs
      have hmem : deltaSub p.1 (eqvClass Φ p.1 p.2) p.1 = eqvClass Φ p.1 p.2 := by
        simp [deltaSub, Function.update_self]
      rw [hmem, mem_eqvClass, mem_eqvClass]
      have hTxy : (Φ p.1).r (T x) (T y) := htl t p.1 T hT x y hxy
      exact ⟨fun h => (Φ p.1).trans h hTxy,
        fun h => (Φ p.1).trans h ((Φ p.1).symm hTxy)⟩
    · have hmem : deltaSub p.1 (eqvClass Φ p.1 p.2) s' = ∅ := by
        simp [deltaSub, Function.update_of_ne hs]
      rw [hmem]
      simp
  · intro h
    have hx : x ∈ deltaSub t (eqvClass Φ t x) t := by
      rw [show deltaSub t (eqvClass Φ t x) t = eqvClass Φ t x from by
        simp [deltaSub, Function.update_self]]
      exact (Φ t).refl x
    have h2 := (h ⟨t, x⟩ t id (TlGen.refl t)).mp hx
    rw [show deltaSub t (eqvClass Φ t x) t = eqvClass Φ t x from by
      simp [deltaSub, Function.update_self]] at h2
    exact h2

/-! ### `B-P028`: pullback of a cogenerated congruence along a homomorphism. -/

/-- For a sorted map `f`, transporting an element along a sort equality commutes
with `f` (dependent-function naturality of `Eq.rec`). -/
theorem sortedMap_cast {S : Type u} {A B : SSet S} (f : SortedMap A B) {u v : S}
    (e : u = v) (x : A v) :
    f u ((congrArg A e).symm ▸ x) = (congrArg B e).symm ▸ (f v x) := by
  cases e
  rfl

/-- A homomorphism maps an elementary translation to an elementary translation
intertwining it. -/
theorem isElemTranslation_map {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f) {t s : S}
    {V : A.1 t → A.1 s} (hV : IsElemTranslation Sig A t s V) :
    ∃ U : B.1 t → B.1 s,
      IsElemTranslation Sig B t s U ∧ ∀ z : A.1 t, U (f t z) = f s (V z) := by
  obtain ⟨w, i, hwit, σ, c, hVform⟩ := (isElemTranslation_insert Sig A t s V).mp hV
  refine ⟨fun y => B.2 (w, s) σ (insertTuple i hwit y (fun k hk => f (w.get k) (c k hk))),
    ⟨w, i, hwit, σ, (fun k hk => f (w.get k) (c k hk)), fun y => rfl⟩, fun z => ?_⟩
  have htup : (fun k => f (w.get k) (insertTuple i hwit z c k))
      = insertTuple i hwit (f t z) (fun k hk => f (w.get k) (c k hk)) := by
    funext k
    by_cases hk : k = i
    · simp only [insertTuple, dif_pos hk]
      exact sortedMap_cast f ((congrArg (fun j : Fin w.length => w.get j) hk).trans hwit) z
    · simp only [insertTuple, dif_neg hk]
  rw [hVform z, hf (w, s) σ (insertTuple i hwit z c), htup]

/-- A homomorphism maps a translation to a translation intertwining it. -/
theorem tlGen_map {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f) {t s : S}
    {V : A.1 t → A.1 s} (hV : TlGen Sig A t s V) :
    ∃ U : B.1 t → B.1 s, TlGen Sig B t s U ∧ ∀ z : A.1 t, U (f t z) = f s (V z) := by
  induction hV with
  | refl t => exact ⟨id, TlGen.refl t, fun z => rfl⟩
  | elem hE =>
      obtain ⟨U, hU, hUf⟩ := isElemTranslation_map Sig hf hE
      exact ⟨U, TlGen.elem hU, hUf⟩
  | comp hT hU ihT ihU =>
      obtain ⟨U1, hU1, hU1f⟩ := ihT
      obtain ⟨U2, hU2, hU2f⟩ := ihU
      exact ⟨U2 ∘ U1, TlGen.comp hU1 hU2, fun z => by
        simp only [Function.comp_apply, hU1f z, hU2f]⟩

/-- An epimorphism lifts an elementary translation to an elementary translation
intertwining it. -/
theorem isElemTranslation_lift {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f)
    (hsurj : ∀ s, Function.Surjective (f s)) {t s : S} {U : B.1 t → B.1 s}
    (hU : IsElemTranslation Sig B t s U) :
    ∃ V : A.1 t → A.1 s,
      IsElemTranslation Sig A t s V ∧ ∀ z : A.1 t, f s (V z) = U (f t z) := by
  obtain ⟨w, i, hwit, σ, c, hUform⟩ := (isElemTranslation_insert Sig B t s U).mp hU
  classical
  let c' : ∀ k : Fin w.length, k ≠ i → A.1 (w.get k) :=
    fun k hk => Classical.choose (hsurj (w.get k) (c k hk))
  have hc' : ∀ k hk, f (w.get k) (c' k hk) = c k hk :=
    fun k hk => Classical.choose_spec (hsurj (w.get k) (c k hk))
  refine ⟨fun z => A.2 (w, s) σ (insertTuple i hwit z c'),
    ⟨w, i, hwit, σ, c', fun z => rfl⟩, fun z => ?_⟩
  have htup : insertTuple i hwit (f t z) c
      = (fun k => f (w.get k) (insertTuple i hwit z c' k)) := by
    funext k
    by_cases hk : k = i
    · simp only [insertTuple, dif_pos hk]
      exact (sortedMap_cast f ((congrArg (fun j : Fin w.length => w.get j) hk).trans hwit) z).symm
    · simp only [insertTuple, dif_neg hk]
      exact (hc' k hk).symm
  have hVeq : f s (A.2 (w, s) σ (insertTuple i hwit z c'))
      = B.2 (w, s) σ (fun k => f (w.get k) (insertTuple i hwit z c' k)) :=
    hf (w, s) σ (insertTuple i hwit z c')
  rw [hUform (f t z), hVeq, htup]

/-- An epimorphism lifts a translation to a translation intertwining it. -/
theorem tlGen_lift {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f)
    (hsurj : ∀ s, Function.Surjective (f s)) {t s : S} {U : B.1 t → B.1 s}
    (hU : TlGen Sig B t s U) :
    ∃ V : A.1 t → A.1 s, TlGen Sig A t s V ∧ ∀ z : A.1 t, f s (V z) = U (f t z) := by
  induction hU with
  | refl t => exact ⟨id, TlGen.refl t, fun z => rfl⟩
  | elem hE =>
      obtain ⟨V, hV, hVf⟩ := isElemTranslation_lift Sig hf hsurj hE
      exact ⟨V, TlGen.elem hV, hVf⟩
  | comp hT hU ihT ihU =>
      obtain ⟨V1, hV1, hV1f⟩ := ihT
      obtain ⟨V2, hV2, hV2f⟩ := ihU
      exact ⟨V2 ∘ V1, TlGen.comp hV1 hV2, fun z => by
        simp only [Function.comp_apply, hV1f z, hV2f]⟩

/-- The pullback `(f×f)⁻¹[Ψ]` of a sorted relation along a sorted map. -/
@[instance_reducible]
def pullbackEqv {S : Type u} {A B : SSet S} (f : SortedMap A B) (Ψ : SortedEqv B) :
    SortedEqv A :=
  fun s =>
    ⟨fun x y => (Ψ s).r (f s x) (f s y),
     ⟨fun x => (Ψ s).refl (f s x),
      fun h => (Ψ s).symm h,
      fun h1 h2 => (Ψ s).trans h1 h2⟩⟩

/-- `B-P028`, first part: for a homomorphism `f : A → B`,
`(f×f)⁻¹[Ω^B(M)] ⊆ Ω^A(f⁻¹[M])`. -/
theorem pullbackEqv_congCogenerated_le {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f) (M : Sub B.1) :
    sortedEqvLe (pullbackEqv f (congCogenerated Sig B M))
      (congCogenerated Sig A (inverseImage f M)) := by
  intro t x y hxy s' V hV
  obtain ⟨U, hU, hUf⟩ := tlGen_map Sig hf hV
  have h := hxy s' U hU
  change f s' (V x) ∈ M s' ↔ f s' (V y) ∈ M s'
  rw [← hUf x, ← hUf y]
  exact h

/-- `B-P028`, second part: if `f` is an epimorphism, the pullback is an equality:
`Ω^A(f⁻¹[M]) ⊆ (f×f)⁻¹[Ω^B(M)]`. -/
theorem congCogenerated_le_pullback_of_surj {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    {f : SortedMap A.1 B.1} (hf : IsAlgHom Sig A.2 B.2 f)
    (hsurj : ∀ s, Function.Surjective (f s)) (M : Sub B.1) :
    sortedEqvLe (congCogenerated Sig A (inverseImage f M))
      (pullbackEqv f (congCogenerated Sig B M)) := by
  intro t x y hxy s' U hU
  obtain ⟨V, hV, hVf⟩ := tlGen_lift Sig hf hsurj hU
  have h := hxy s' V hV
  rw [← hVf x, ← hVf y]
  exact h

/-! ### `B-R021`: `Ω` is a natural transformation `P⁻ ⇒ Cgr`. -/

/-- The identity is an algebra homomorphism. -/
theorem isAlgHom_id {S : Type u} (Sig : Signature S) {A : SSet S} (FA : AlgStruct Sig A) :
    IsAlgHom Sig FA FA (fun _ => id) := by
  intro p σ a
  rfl

/-- Composition of algebra homomorphisms is an algebra homomorphism. -/
theorem isAlgHom_comp {S : Type u} (Sig : Signature S) {A B C : SSet S}
    {FA : AlgStruct Sig A} {FB : AlgStruct Sig B} {FC : AlgStruct Sig C}
    {f : SortedMap A B} {g : SortedMap B C}
    (hf : IsAlgHom Sig FA FB f) (hg : IsAlgHom Sig FB FC g) :
    IsAlgHom Sig FA FC (fun s => g s ∘ f s) := by
  intro p σ a
  simp only [Function.comp_apply]
  rw [hf p σ a, hg p σ (fun i => f (p.1.get i) (a i))]

/-- Two sorted equivalences that refine each other are equal. -/
theorem sortedEqvLe_antisymm {S : Type u} {A : SSet S} {Φ Ψ : SortedEqv A}
    (h₁ : sortedEqvLe Φ Ψ) (h₂ : sortedEqvLe Ψ Φ) : Φ = Ψ := by
  funext s
  exact Setoid.ext (fun x y => ⟨h₁ s x y, h₂ s x y⟩)

/-- `B-R021`: a morphism of `Alg(Σ)_epi`, i.e. an epimorphism of `Σ`-algebras:
a homomorphism whose every component is surjective. -/
structure AlgEpi {S : Type u} (Sig : Signature S) (A B : Alg Sig) where
  map : SortedMap A.1 B.1
  hom : IsAlgHom Sig A.2 B.2 map
  surj : ∀ s, Function.Surjective (map s)

/-- `B-R021`: the identity epimorphism. -/
def AlgEpiId {S : Type u} (Sig : Signature S) (A : Alg Sig) : AlgEpi Sig A A where
  map := fun _ => id
  hom := isAlgHom_id Sig A.2
  surj := fun _ => Function.surjective_id

/-- `B-R021`: composition of epimorphisms. -/
def AlgEpiComp {S : Type u} (Sig : Signature S) {A B C : Alg Sig}
    (g : AlgEpi Sig B C) (f : AlgEpi Sig A B) : AlgEpi Sig A C where
  map := fun s => g.map s ∘ f.map s
  hom := isAlgHom_comp Sig f.hom g.hom
  surj := fun s => (g.surj s).comp (f.surj s)

/-- Two epimorphisms with the same underlying map are equal (the `hom` and
`surj` fields are propositions). -/
@[ext]
theorem AlgEpiExt {S : Type u} {Sig : Signature S} {A B : Alg Sig}
    {f g : AlgEpi Sig A B} (h : f.map = g.map) : f = g := by
  obtain ⟨fm, fh, fs⟩ := f
  obtain ⟨gm, gh, gs⟩ := g
  simp only at h
  subst h
  congr

/-- `B-R021`: the identity epimorphism is a left identity for composition. -/
theorem AlgEpiComp_id_left {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    (f : AlgEpi Sig A B) : AlgEpiComp Sig (AlgEpiId Sig B) f = f :=
  AlgEpiExt (by funext s x; rfl)

/-- `B-R021`: the identity epimorphism is a right identity for composition. -/
theorem AlgEpiComp_id_right {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    (f : AlgEpi Sig A B) : AlgEpiComp Sig f (AlgEpiId Sig A) = f :=
  AlgEpiExt (by funext s x; rfl)

/-- `B-R021`: composition of epimorphisms is associative. -/
theorem AlgEpiComp_assoc {S : Type u} (Sig : Signature S) {A B C D : Alg Sig}
    (h : AlgEpi Sig C D) (g : AlgEpi Sig B C) (f : AlgEpi Sig A B) :
    AlgEpiComp Sig (AlgEpiComp Sig h g) f = AlgEpiComp Sig h (AlgEpiComp Sig g f) :=
  AlgEpiExt (by funext s x; rfl)

/-- `B-R021`: the functor `P⁻` on morphisms, `L ↦ f⁻¹[L]`. -/
def SubMap {S : Type u} (Sig : Signature S) {A B : Alg Sig} (f : AlgEpi Sig A B) :
    Sub B.1 → Sub A.1 :=
  inverseImage f.map

/-- `B-R021`: the functor `Cgr` on morphisms, `Φ ↦ (f×f)⁻¹[Φ]`. -/
@[instance_reducible]
def CgrMap {S : Type u} (Sig : Signature S) {A B : Alg Sig} (f : AlgEpi Sig A B) :
    SortedEqv B.1 → SortedEqv A.1 :=
  pullbackEqv f.map

/-- `B-R021`: `P⁻` preserves identities. -/
theorem SubMap_id {S : Type u} (Sig : Signature S) (A : Alg Sig) :
    SubMap Sig (AlgEpiId Sig A) = id := by
  funext Y s x
  rfl

/-- `B-R021`: `P⁻` reverses composition (contravariance). -/
theorem SubMap_comp {S : Type u} (Sig : Signature S) {A B C : Alg Sig}
    (g : AlgEpi Sig B C) (f : AlgEpi Sig A B) :
    SubMap Sig (AlgEpiComp Sig g f) = SubMap Sig f ∘ SubMap Sig g := by
  funext Z s x
  rfl

/-- `B-R021`: `Cgr` preserves identities. -/
theorem CgrMap_id {S : Type u} (Sig : Signature S) (A : Alg Sig) :
    CgrMap Sig (AlgEpiId Sig A) = id := by
  funext Ψ s
  apply Setoid.ext
  intro x y
  exact Iff.rfl

/-- `B-R021`: `Cgr` reverses composition (contravariance). -/
theorem CgrMap_comp {S : Type u} (Sig : Signature S) {A B C : Alg Sig}
    (g : AlgEpi Sig B C) (f : AlgEpi Sig A B) :
    CgrMap Sig (AlgEpiComp Sig g f) = CgrMap Sig f ∘ CgrMap Sig g := by
  funext Θ s
  apply Setoid.ext
  intro x y
  exact Iff.rfl

/-- `B-R021`: `Ω` is natural. For an epimorphism `f : A → B` and `M ∈ Sub(B)`,
`(f×f)⁻¹[Ω^B(M)] = Ω^A(f⁻¹[M])`. The two inclusions are the two halves of
`B-P028`. -/
theorem congCogenerated_natural {S : Type u} (Sig : Signature S) {A B : Alg Sig}
    (f : AlgEpi Sig A B) (M : Sub B.1) :
    CgrMap Sig f (congCogenerated Sig B M) = congCogenerated Sig A (SubMap Sig f M) :=
  sortedEqvLe_antisymm
    (pullbackEqv_congCogenerated_le Sig f.hom M)
    (congCogenerated_le_pullback_of_surj Sig f.hom f.surj M)

end Mslang
